name: Test TXT Deploy

on:
  push:
    branches:
      - master  # Проверь, что ветка в GitHub называется именно main!

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Pull TXT
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/debian/test-deploy
            git pull origin main
            ls -la
            cat test_gitHub-actions.txt